### ISSUE TITLE
xhr get json and assign to variable?

### ISSUE THREAD

**Issue by orschiro** [orschiro/reddit-karma-chrome#2]
@dushmis do you have any idea how to use `xhr` to get the json and write its content to a variable `karma`?

See this [1].

[1] https://github.com/orschiro/reddit-karma-chrome/commit/0cb858cb8ce6d22a04d5e930a236e59530f4e2fb

Thank you for your help!

**Comment by dushmis** [comment]
Why don't you put `chrome.browserAction.setBadgeText({ text: karma });` inside ajax call and
get comment karma like this `karma.data.comment_karma`

**Comment by dushmis** [comment]
Since you're passing `true` in `xhr.open`'s third parameter, it is async method ( which makes sense as we want that request to be completed in background and doesn't want to block any other operation). So whatever operation you want to perform you either need to pass a function to a function that does network operation or you'll have to do your work inside where you get the XHR response, ideally in `if (xhr.readyState == 4) { /* here */ }`

**Comment by orschiro** [comment]
@dushmis you're super helpful, thanks!

See https://github.com/orschiro/reddit-karma-chrome/commit/bda04b9efdaa9db1366ace0d6cad5dda8cd7a8f1

>  So whatever operation you want to perform you either need to pass a function to a function that does network operation or you'll have to do your work inside where you get the XHR response, ideally in if (xhr.readyState == 4) { /* here */ }

Can you clarify this a bit more? Not sure I understand.

**Comment by dushmis** [comment]
Check [this](https://github.com/dushmis/reddit-karma-chrome/blob/master/src/background.js) out

**Comment by dushmis** [comment]
@orschiro Have you figured it out yet?

**Comment by orschiro** [comment]
@dushmis you're amazing! :-)

See these: https://github.com/orschiro/reddit-karma-chrome/commit/4958bebf573ea98903324fa52fff9edc24bd7d01, https://github.com/orschiro/reddit-karma-chrome/commit/4c14138dd7ad7064797a87e7b1aeb4ffc7ae3cdd

:-)

Shall we release this extension to the Chrome Webstore? 

I like it a lot. It's cool to see the karma. :-D

Thank thank you for your contribution!

**Comment by dushmis** [comment]
haha, don't we need more feature for this to go live? ;-)

**Comment by orschiro** [comment]
Haha, don't know. I am very happy with the counter going up. :-D

What feature are you missing?

Maybe opening the user profile page upon click of the icon?

**Comment by dushmis** [comment]
1. It isn't working well on Mac, it just shows three characters ( so i guess it needs to have some kind of popup where it displays karma breakup )
2. notifications if karma goes up. ( alert users if they get upvotes ? via chrome notifications ? )
3. ~~their home page in reddit in popup so they don't have to open reddit ?~~ 
4. ~~so on and on...~~

**Comment by orschiro** [comment]
@dushmis let's split those into separate issues!

> It isn't working well on Mac, it just shows three characters ( so i guess it needs to have some kind of popup where it displays karma breakup )

https://github.com/orschiro/reddit-karma-chrome/issues/3

> notifications if karma goes up. ( alert users if they get upvotes ? via chrome notifications ? )

https://github.com/orschiro/reddit-karma-chrome/issues/4
